### ISSUE TITLE
MIT & GPL Confusion

### ISSUE THREAD

**Issue by iocron** [tabacitu/dick#46]
Hello,
on Packalyst is dick under the MIT License, but on Github on GPL. Some of the Modules (e.g. https://github.com/tabacitu/menumanager, etc.) are under the MIT License as well. So is this a dual licensing? Which one counts? At least for me the MIT License would be more preferable.

Kind regards,
dk

**Comment by tabacitu** [comment]
Hi @iocron ,

Thanks for the tip, it's fixed now, MIT everywhere. But you needn't to worry about the license. Let this be a legally biding document:

```
I hereby give you permission to do whatever the fuck you want with the Dick open source packages.
``` 

There, this should fix it. Also, soon we're launching v2, called Backpack instead of Dick, which can also be installed on existing projects. Might want to check it out in a few weeks.

https://github.com/laravel-backpack

Cheers!
