### ISSUE TITLE
A lot of errors when upgrading Laravel 5.2

### ISSUE THREAD

**Issue by Vagabondtq** [tabacitu/dick#56]
When I use the Laravel 5.2 generated a lot of bugs are not compatible:
Eg: Interface 'Illuminate \ Contracts \ Routing \ Middleware' not found

When will you upgrade to run with Laravel 5.2?

**Comment by tabacitu** [comment]
Hi @Vagabondtq,

Since 5.1 is tagged by Taylor as long-time-support, that's what we'll do with Dick and Backpack too:
- Dick - 5.1, maintenance only, keep long-time-support
- Backpack - 5.2+, new features (https://github.com/Laravel-Backpack/ - beta launch at the end of the month, most likely)

Laravel Backpack is basically Dick v2, for Laravel 5.2+. You'll like it, I promise.
